language: rust
sudo: false
rust:
- stable
- nightly
- beta
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo build
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
