language: c

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: BUILD_TYPE=docker
           DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           SUFFIX=x86_64
    - sudo: required
      services:
        - docker
      env: BUILD_TYPE=docker
           DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           SUFFIX=i686
    - os: linux
      env: BUILD_TYPE=make
    - os: linux
      env: BUILD_TYPE=cmake
    - os: osx
      env: BUILD_TYPE=cmake
           MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: linux
      env: BUILD_TYPE=make
           MAYBE_CROSS="--host=arm-linux-gnueabihf --enable-static --disable-shared --without-zlib"
           MY_CFLAGS=-O2
           MY_CC=arm-linux-gnueabihf-gcc
           MY_CXX=arm-linux-gnueabihf-g++
      addons:
        apt:
          packages:
          - gcc-arm-linux-gnueabihf
          - g++-arm-linux-gnueabihf
    - os: linux
      env: BUILD_TYPE=make
           MAYBE_CROSS="--host=aarch64-linux-gnu --enable-static --disable-shared --without-zlib"
           MY_CFLAGS=-O2
           MY_CC=aarch64-linux-gnu-gcc
           MY_CXX=aarch64-linux-gnu-g++
      addons:
        apt:
          packages:
          - gcc-aarch64-linux-gnu
          - g++-aarch64-linux-gnu
    - os: linux
      env: BUILD_TYPE=make
           MAYBE_CROSS="--host=powerpc-linux-gnu --enable-static --disable-shared --without-zlib"
           MY_CFLAGS=-O2
           MY_CC=powerpc-linux-gnu-gcc
           MY_CXX=powerpc-linux-gnu-g++
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu
          - g++-powerpc-linux-gnu
    - os: linux
      env: BUILD_TYPE=make
           MAYBE_CROSS="--host=arm-linux-gnueabi --enable-static --disable-shared --without-zlib"
           MY_CFLAGS=-O2
           MY_CC=arm-linux-gnueabi-gcc
           MY_CXX=arm-linux-gnueabi-g++
      addons:
        apt:
          packages:
          - gcc-arm-linux-gnueabi
          - g++-arm-linux-gnueabi
  allow_failures:
    - env: BUILD_TYPE=make
           MAYBE_CROSS="--host=powerpc-linux-gnu --enable-static --disable-shared --without-zlib"
           MY_CFLAGS=-O2
           MY_CC=powerpc-linux-gnu-gcc
           MY_CXX=powerpc-linux-gnu-g++
    - env: BUILD_TYPE=make
           MAYBE_CROSS="--host=arm-linux-gnueabi --enable-static --disable-shared --without-zlib"
           MY_CFLAGS=-O2
           MY_CC=arm-linux-gnueabi-gcc
           MY_CXX=arm-linux-gnueabi-g++

###
## If we use the matrix to set CC/CXX Travis overwrites the values,
## so instead we use MY_CC/CXX, then copy the values to CC/CXX
## here (after Travis has set CC/CXX).
###
before_install:
  - if [[ -n "${MY_CC}" ]]; then export CC="${MY_CC}"; fi
  - if [[ -n "${MY_CXX}" ]]; then export CXX="${MY_CXX}"; fi
  - if [[ -n "${MY_CFLAGS}" ]]; then export CFLAGS="${MY_CFLAGS}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable || true; fi

install:
  - if [[ "$BUILD_TYPE" == "docker" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ -n "${MY_CC}" ]]; then export CC="${MY_CC}"; fi
  - if [[ -n "${MY_CXX}" ]]; then export CXX="${MY_CXX}"; fi
  - if [[ -n "${MY_CFLAGS}" ]]; then export CFLAGS="${MY_CFLAGS}"; fi
  - if [[ "$BUILD_TYPE" == "docker" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-docker.sh $SUFFIX; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then autoreconf -fi; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then ./configure $MAYBE_CROSS || cat config.log; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then make -j 4; fi
  - if [[ "$BUILD_TYPE" == "make" && "x${MAYBE_CROSS}" != x ]]; then make check -j 4; fi
  - if [[ "$BUILD_TYPE" == "make" && "x${MAYBE_CROSS}" = x ]]; then make distcheck -j 4; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then make dist; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then make dist-zip; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then mkdir dist; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then mv parasail-*.tar.gz dist; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then mv parasail-*.zip dist; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake . $MAYBE_ARCH; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release --target package; fi

deploy:
  provider: releases
  api_key:
    secure: t+xGKs6b/Jof6lJZola9qhPsw6YE4lVVlYc1BdoFE25V+aAGtNrunZ6gV0E5Yw30dl4j/WuzSF7MWlNT3eJqXeNMkXIMigvZVRkXuyB1G92d+5vMPpOKyAWP99/LbeKepzo7Q6bP64nY8vfIgnRYCr+a1NhWUxJjopVASMBXTjwaBCyGz8njpn61zTuSNT+u0lmHeVYNZTdR1/5um9P2CF1UcSK2hCuWbwkSU0RsdogHhsjfdk2N9vwH17+ETptkz8P5tLl7VmvXoFFsAUAeRJ1OZrVVO2Cqc6eEeG9mmdzm8arZ0PuSrI3uLWvrsjfD+zOGp2VoiVXiHw0gulnW/ALiai9r6J3mlTg0yueT2fQpoaT8NYjh+Yz2A5KLxFvmPRzvoesQ5QjjoHBSj6HdUXlI8ezgqu3tMQSYhySizFr5CK2a4bOPok50nsht/OHCdr7F9+m5bjZfiKoinp7l23zLMqnIf/sbW/Obx/iU+VgvbuFFCG3ZUJaNosTlei856gFCOMgJ2j+MIPymvUBgOszbGhC9X2m0iwkit59SieqQCvWW1BHNrsYRXIegcbJCDl6ZEzbjSa/7mijggU+x+WTHK8bK3GXSpO34NLvehKI8nc0DhdMKCyO563TRUGWjdBSohSd8Bl6TgxJQXqrijcqdoNjxfPlrgFZXoXMA9vs=
  file: dist/*
  skip_cleanup: true
  file_glob: true
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    repo: jeffdaily/parasail
    tags: true
    condition: $TRAVIS_OS_NAME = "osx" || $BUILD_TYPE = "docker" || $BUILD_TYPE = "make" && "x$MAYBE_CROSS" = "x"

